---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * 0"

defaults:
  run:
    working-directory: 'eirikns.users'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v5
        with:
          path: 'eirikns.users'

      - name: Set up Python 3.
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install test dependencies.
        run: |
          pip3 install ansible-lint
          ansible-galaxy install -r requirements.yaml

      - name: Lint code.
        run: |
          ansible-lint

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian13
          - ubuntu2404
          - ubuntu2604
        scenario:
          - default
          - sudo_require_password
          - sudo_require_password_precheck

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v5
        with:
          path: 'eirikns.users'

      - name: Set up Python 3.
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] docker

      - name: Run Molecule tests.
        run: molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
